# C) Gov 10a exp page linear

In [1]:
import numpy as np

Realizamos la lectura de todos los registros del data set.

In [2]:
data = np.loadtxt('data/gov_10a_exp_page_linear.csv', delimiter=',', skiprows=1, dtype=[('DATAFLOW', np.unicode_, 50), ('LAST UPDATE', np.unicode_, 40), ('freq', np.unicode_, 12), ('unit', np.unicode_, 12), ('sector', np.unicode_, 12), ('cofog99', np.unicode_, 12), ('na_item', np.unicode_, 12), ('geo', np.unicode_, 12), ('TIME_PERIOD', 'i4'), ('OBS_VALUE', 'f4'), ('OBS_FLAG', np.unicode_, 12)])
print("Este conjunto de datos tiene un total de ", data.shape[0], " registros")

Este conjunto de datos tiene un total de  282  registros


In [3]:
print(data[:5])

[('ESTAT:GOV_10A_EXP$DEFAULTVIEW(1.0)', '03/01/23 11:00:00', 'A', 'PC_GDP', 'S13', 'TOTAL', 'TE', 'AT', 2012, 51.2, '')
 ('ESTAT:GOV_10A_EXP$DEFAULTVIEW(1.0)', '03/01/23 11:00:00', 'A', 'PC_GDP', 'S13', 'TOTAL', 'TE', 'AT', 2013, 51.6, '')
 ('ESTAT:GOV_10A_EXP$DEFAULTVIEW(1.0)', '03/01/23 11:00:00', 'A', 'PC_GDP', 'S13', 'TOTAL', 'TE', 'AT', 2014, 52.4, '')
 ('ESTAT:GOV_10A_EXP$DEFAULTVIEW(1.0)', '03/01/23 11:00:00', 'A', 'PC_GDP', 'S13', 'TOTAL', 'TE', 'AT', 2015, 51.1, '')
 ('ESTAT:GOV_10A_EXP$DEFAULTVIEW(1.0)', '03/01/23 11:00:00', 'A', 'PC_GDP', 'S13', 'TOTAL', 'TE', 'AT', 2016, 50.1, '')]


Una vez tenemos el dataset en nuestro local storage vamos a realizar un pequeño estudio sobre los datos para ver que es lo que podemos sacar de ellos.

Primero de todos vamos a ver cuantos registros diferentes hay de cada una de las columnas, ya que a primera vista parece que tenemos muchas variables con un solo valor.

In [4]:
print("De la variable freq tenemos un total de ", np.unique(data['freq']).shape[0], " registros diferentes")
print("De la variable DATAFLOW tenemos un total de ", np.unique(data['DATAFLOW']).shape[0], " registros diferentes")
print("De la variable LAST UPDATE tenemos un total de ", np.unique(data['LAST UPDATE']).shape[0], " registros diferentes")
print("De la variable unit tenemos un total de ", np.unique(data['unit']).shape[0], " registros diferentes")
print("De la variable sector tenemos un total de ", np.unique(data['sector']).shape[0], " registros diferentes")
print("De la variable cofog99 tenemos un total de ", np.unique(data['cofog99']).shape[0], " registros diferentes")
print("De la variable geo tenemos un total de ", np.unique(data['geo']).shape[0], " registros diferentes")
print("De la variable na_item tenemos un total de ", np.unique(data['na_item']).shape[0], " registros diferentes")
print("De la variable TIME_PERIOD tenemos un total de ", np.unique(data['TIME_PERIOD']).shape[0], " registros diferentes")
print("De la variable OBS_FLAG tenemos un total de ", np.unique(data['OBS_FLAG']).shape[0], " registros diferentes")

De la variable freq tenemos un total de  1  registros diferentes
De la variable DATAFLOW tenemos un total de  1  registros diferentes
De la variable LAST UPDATE tenemos un total de  1  registros diferentes
De la variable unit tenemos un total de  1  registros diferentes
De la variable sector tenemos un total de  1  registros diferentes
De la variable cofog99 tenemos un total de  1  registros diferentes
De la variable geo tenemos un total de  31  registros diferentes
De la variable na_item tenemos un total de  1  registros diferentes
De la variable TIME_PERIOD tenemos un total de  10  registros diferentes
De la variable OBS_FLAG tenemos un total de  3  registros diferentes


Por tanto solo nos interesaran los registros geo, TIME_PERIOD y OBS_FLAG, ya que los otros registros no podrán darnos ninguna información sobre los datos.

Vamos a empezar a trabajar con la variable **geo** que se refiere a la zona. Primero de todo vamos a obtener los registros únicos que tenemos y realizar una agrupación de esta para obtener información sobre el **OBS_VALUE**.

In [5]:
geo = data['geo']
geonames, indices = np.unique(geo, return_inverse=True) 

In [6]:
print(geonames)

['AT' 'BE' 'BG' 'CY' 'CZ' 'DE' 'DK' 'EA19' 'EE' 'EL' 'ES' 'EU27_2020' 'FI'
 'FR' 'HR' 'HU' 'IE' 'IS' 'IT' 'LT' 'LU' 'LV' 'MT' 'NL' 'NO' 'PL' 'PT'
 'RO' 'SE' 'SI' 'SK']


In [7]:
# Realizamos la suma del OBS_VALUE por zona
np.bincount(indices, data['OBS_VALUE'])

array([515.79999542, 490.19999695, 339.5       , 375.40000153,
       379.59999847, 406.90000153, 531.        , 439.70000458,
       358.20000839, 478.90000153, 403.30000305, 436.40000153,
       499.29999542, 514.09999847, 431.20000458, 436.39999771,
       280.99999809, 411.40000153, 454.69999695, 320.80000305,
       377.5       , 351.5       , 350.00000381, 449.59999084,
       444.19999695, 384.79999542, 423.90000534, 324.20000076,
       452.70000076, 437.59999847, 381.39999771])

La función anterior no nos ha dado mucha información sobre los datos, creo que sería mejor obtener la media y la mediana por zona.

In [8]:
countries = data['geo']
countries_obsVal = [(i, round(data['OBS_VALUE'][countries == i].mean(), 2)) for i in geonames]

In [9]:
print("La mediana del OBS_VALUE por zona es:\n", countries_obsVal)

La mediana del OBS_VALUE por zona es:
 [('AT', 51.58), ('BE', 54.47), ('BG', 37.72), ('CY', 41.71), ('CZ', 42.18), ('DE', 45.21), ('DK', 53.1), ('EA19', 48.86), ('EE', 39.8), ('EL', 53.21), ('ES', 44.81), ('EU27_2020', 48.49), ('FI', 55.48), ('FR', 57.12), ('HR', 47.91), ('HU', 48.49), ('IE', 31.22), ('IS', 45.71), ('IT', 50.52), ('LT', 35.64), ('LU', 41.94), ('LV', 39.06), ('MT', 38.89), ('NL', 44.96), ('NO', 49.36), ('PL', 42.76), ('PT', 47.1), ('RO', 36.02), ('SE', 50.3), ('SI', 48.62), ('SK', 42.38)]


In [10]:
# Vamos a realizar una ordenación sobre estos datos
countries_obsVal = np.array(countries_obsVal, dtype=[('geo', np.unicode_, 12), ('OBS_VALUE', np.float64)])
countries_obsVal_Asc = np.sort(countries_obsVal, order='OBS_VALUE')

In [11]:
print("Ordenación ascendente (head): ", countries_obsVal_Asc[:5])

Ordenación ascendente (head):  [('IE', 31.21999931) ('LT', 35.63999939) ('RO', 36.02000046)
 ('BG', 37.72000122) ('MT', 38.88999939)]


In [12]:
print("Ordenación ascendente (tail): ", countries_obsVal_Asc[-5:])

Ordenación ascendente (tail):  [('DK', 53.09999847) ('EL', 53.20999908) ('BE', 54.47000122)
 ('FI', 55.47999954) ('FR', 57.11999893)]


In [13]:
print("Por tanto, según la ordenación anterior la zona con el OBS_VALUE más pequeño es ", countries_obsVal_Asc[:1][0][0], "con un valor medio de ", round(countries_obsVal_Asc[:1][0][1], 2))
print("Por otra partem la zona con un OBS_VALUE mayor es ", countries_obsVal_Asc[-1:][0][0], " con un valor medio de ", round(countries_obsVal_Asc[-1:][0][1], 2))

Por tanto, según la ordenación anterior la zona con el OBS_VALUE más pequeño es  IE con un valor medio de  31.22
Por otra partem la zona con un OBS_VALUE mayor es  FR  con un valor medio de  57.12


Ahora vamos a ver que tal el valor de la zona de España, abreviada como 'ES'.

In [14]:
espana = 'ES'
mask = countries_obsVal['geo'] == espana
print("El valor del OBS_VALUE en españa se encuentra en ", countries_obsVal[mask])

El valor del OBS_VALUE en españa se encuentra en  [('ES', 44.81000137)]


Ahora vamos a empezar a trabajar con los años, **TIME_PERIOD**. Vamos a ver si hay algún tipo de relación entre el **TIME_PERIOD** y el **OBS_VALUE**.

In [15]:
obsValueByGeoAndPeriod = data[['geo', 'TIME_PERIOD', 'OBS_VALUE', 'OBS_FLAG']]

In [16]:
obsValuePeriodOrdAsc = np.sort(obsValueByGeoAndPeriod, order='OBS_VALUE')
print("Como vemos, según el muestreo, estos son los cinco registros con un valor de OBS_VALUE menor:\n", obsValuePeriodOrdAsc[:5])
print("Los mayores son:\n", obsValuePeriodOrdAsc[-5:])

Como vemos, según el muestreo, estos son los cinco registros con un valor de OBS_VALUE menor:
 [('IE', 2019, 24.2, '') ('IE', 2018, 25.3, '') ('IE', 2017, 26.2, '')
 ('IE', 2020, 27.4, '') ('IE', 2016, 28.1, '')]
Los mayores son:
 [('BE', 2020, 59.2, '') ('EL', 2020, 59.8, '') ('SI', 2013, 60.3, '')
 ('FR', 2020, 61.6, 'p') ('EL', 2013, 62.8, '')]


Ahora realizaremos la agrupación por año y obtendremos la media y la desviación típica del OBS_VALUE

In [17]:
tp, idx = np.unique(obsValueByGeoAndPeriod["TIME_PERIOD"], return_inverse=True)
time_period = obsValueByGeoAndPeriod["TIME_PERIOD"]
year_obsVal_mean = np.array([(i, np.mean((obsValueByGeoAndPeriod['OBS_VALUE'][time_period == i]))) for i in tp])

In [18]:
print("La mediana del OBS_VALUE de cada año registrado es:\n", year_obsVal_mean)

La mediana del OBS_VALUE de cada año registrado es:
 [[2012.           46.64516449]
 [2013.           47.06774139]
 [2014.           46.56452179]
 [2015.           45.53225327]
 [2016.           44.23225784]
 [2017.           43.34516144]
 [2018.           43.60000229]
 [2019.           43.49354935]
 [2020.           50.09354401]
 [2021.           51.1333313 ]]


In [19]:
year_obsVal_std = np.array([(i, np.std((obsValueByGeoAndPeriod['OBS_VALUE'][time_period == i]))) for i in tp])
print("La desviación típica del OBS_VALUE de cada año registrado es:\n", year_obsVal_std)

La desviación típica del OBS_VALUE de cada año registrado es:
 [[2012.            6.33499479]
 [2013.            7.0906291 ]
 [2014.            6.14893436]
 [2015.            6.54642916]
 [2016.            6.75513554]
 [2017.            6.72917843]
 [2018.            6.27293205]
 [2019.            6.38460541]
 [2020.            6.85141563]
 [2021.            3.84476614]]


In [20]:
print("EL mínimo valor medio de los años del df es ", round(year_obsVal_mean[:,1].min(), 2), " que se encuentra en el ", int(year_obsVal_mean[year_obsVal_mean[:,1].argmin()][0]))
print("El máximo OBS_VALUE se encuentra en el año ", int(year_obsVal_mean[year_obsVal_mean[:,1].argmax()][0]), " con un valor del OBS_VALUE de ", round(year_obsVal_mean[:,1].max(), 2), " de media")

EL mínimo valor medio de los años del df es  43.35  que se encuentra en el  2017
El máximo OBS_VALUE se encuentra en el año  2021  con un valor del OBS_VALUE de  51.13  de media
